### PR TITLE
Fix compilation error in CHBgDropboxSync-master

### LINKED ISSUE #172: iNDS doesn't build in Xcode 11.4.1
I get a build error when trying to build the latest version of iNDS in Xcode 11.4.1. The error is:

`Incompatible block pointer types sending 'void (^)(DBFILESMetadata * _Nullable __strong, DBFILESDeleteError * _Nullable __strong, DBRequestError * _Nullable __strong)' to parameter of type 'void (^ _Nonnull)(DBFILESDeleteResult * _Nullable __strong, DBFILESDeleteError * _Nullable __strong, DBRequestError * _Nullable __strong)'`

On line 288 of the file Main -> Dropbox -> CHBgDropboxSync.m

When I comment out lines 288 - 295, then the project builds successfully with no errors.

### PR DESCRIPTION
**Pull request by jdkula**
Fixes #172 and #178. Pulled fresh from my repo and was able to compile it first try using the instructions in the docs.

It appears that an argument type of the block was incorrect -- I just changed it to the correct type as discussed in #172.

### CODE REVIEW

**Comment by FrederickGeek8** [comment]
Thank you for the pull request! Everything checks out so I'll merge.
